In [2]:
import numpy as np
import pandas as pd

train = pd.read_csv('train.csv')
train

id  carat        cut color clarity  depth  table     x     y  \
0            0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33   
1            1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12   
2            2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73   
3            3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41   
4            4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61   
...        ...    ...        ...   ...     ...    ...    ...   ...   ...   
193568  193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39   
193569  193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77   
193570  193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75   
193571  193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49   
193572  193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71   

           z  price  
0       4.55  13619  
1       5.05  13387  
2       3.50   2772  
3       2.71    666  
4       4.77  14453  
...      ...    ...  
193568  2.67   1130  
193569  3.47   2874  
193570  3.62   3036  
193571  2.81    681  
193572  3.48   2258  

[193573 rows x 11 columns]

In [28]:
print(train['cut'].unique()) 
print(train['color'].unique())
print(train['price'].mean())
print(train['carat'].max())
print(train['cut'][train['carat'].idxmax()])
print(np.corrcoef(train['carat'],train['price']))
# train.apply(lambda x: x.factorize()[0]).corr()

['Premium' 'Very Good' 'Ideal' 'Good' 'Fair']
['F' 'J' 'G' 'E' 'D' 'H' 'I']
3969.1554142364894
3.5
Very Good
[[1.        0.9433961]
 [0.9433961 1.       ]]


In [12]:
print(np.corrcoef(train['carat'], train['price']))
print(np.corrcoef(train['depth'], train['price']))
print(np.corrcoef(train['table'], train['price']))
print(np.corrcoef(train['x'], train['price']))
print(np.corrcoef(train['y'], train['price']))
print(np.corrcoef(train['z'], train['price']))






[[1.        0.9433961]
 [0.9433961 1.       ]]
[[1.         0.00187951]
 [0.00187951 1.        ]]
[[1.         0.17491538]
 [0.17491538 1.        ]]
[[1.         0.90100439]
 [0.90100439 1.        ]]
[[1.         0.90103323]
 [0.90103323 1.        ]]
[[1.         0.89303704]
 [0.89303704 1.        ]]


In [31]:
train['cut'][train['carat'] == 3.5]

140193    Very Good
Name: cut, dtype: object

In [5]:
df1 = pd.DataFrame(columns = ['cut', 'color', 'clarity','price'])


In [7]:
df1['cut'] = pd.factorize(train['cut'])[0]
df1['price'] = train['price']
df1

cut color clarity  price
0         0   NaN     NaN  13619
1         1   NaN     NaN  13387
2         2   NaN     NaN   2772
3         2   NaN     NaN    666
4         0   NaN     NaN  14453
...     ...   ...     ...    ...
193568    2   NaN     NaN   1130
193569    0   NaN     NaN   2874
193570    1   NaN     NaN   3036
193571    1   NaN     NaN    681
193572    3   NaN     NaN   2258

[193573 rows x 4 columns]

In [13]:
df1[['cut', 'color', 'clarity']] = train[['cut', 'color', 'clarity']].apply(lambda x: pd.factorize(x)[0])
df1
print(np.corrcoef(df1['cut'], df1['price']))
print(np.corrcoef(df1['color'], df1['price']))
print(np.corrcoef(df1['clarity'], df1['price']))
print(np.corrcoef(df1['clarity'], df1['price']))


[[ 1.         -0.11146232]
 [-0.11146232  1.        ]]
[[1.         0.07534415]
 [0.07534415 1.        ]]
[[ 1.         -0.13217184]
 [-0.13217184  1.        ]]


In [9]:
df1.corr()

cut     color   clarity     price
cut      1.000000 -0.017794  0.063438 -0.111462
color   -0.017794  1.000000 -0.018340  0.075344
clarity  0.063438 -0.018340  1.000000 -0.132172
price   -0.111462  0.075344 -0.132172  1.000000

In [15]:
df2 = train.apply(lambda x: x.factorize()[0]).corr()
df2

id     carat       cut     color   clarity     depth     table  \
id       1.000000  0.003661 -0.003777 -0.003113 -0.001706 -0.001180  0.004604   
carat    0.003661  1.000000 -0.015666  0.032114 -0.073941 -0.019572 -0.000679   
cut     -0.003777 -0.015666  1.000000 -0.017794  0.063438  0.060224  0.111689   
color   -0.003113  0.032114 -0.017794  1.000000 -0.018340 -0.005610  0.004551   
clarity -0.001706 -0.073941  0.063438 -0.018340  1.000000 -0.026680 -0.001000   
depth   -0.001180 -0.019572  0.060224 -0.005610 -0.026680  1.000000  0.075372   
table    0.004604 -0.000679  0.111689  0.004551 -0.001000  0.075372  1.000000   
x        0.005000  0.323648 -0.014175  0.035207 -0.043868  0.095593  0.003566   
y        0.004586  0.304063 -0.003119  0.032931 -0.042901  0.088546  0.015735   
z        0.005903  0.263048 -0.069887  0.034905 -0.038113  0.102002  0.046874   
price    0.056440  0.178841 -0.038430  0.023823 -0.076233  0.038851  0.003438   

                x         y         z     price  
id       0.005000  0.004586  0.005903  0.056440  
carat    0.323648  0.304063  0.263048  0.178841  
cut     -0.014175 -0.003119 -0.069887 -0.038430  
color    0.035207  0.032931  0.034905  0.023823  
clarity -0.043868 -0.042901 -0.038113 -0.076233  
depth    0.095593  0.088546  0.102002  0.038851  
table    0.003566  0.015735  0.046874  0.003438  
x        1.000000  0.351678  0.272441  0.170770  
y        0.351678  1.000000  0.257065  0.159704  
z        0.272441  0.257065  1.000000  0.140709  
price    0.170770  0.159704  0.140709  1.000000

In [ ]:
# color carat x y z
